version: "3.3"
services:
  prefect:
    image: prefecthq/prefect:2.14-python3.11
    container_name: prefect_server
    # command: prefect server start
    command: sleep 99999
    environment:
    - PREFECT_SERVER_API_HOST=0.0.0.0
    - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect_user:${PREFECT_DB_PW}@postgres:5432/prefect # Needed if using postgres and not sqlite
    # - PREFECT_UI_API_URL=http://localhost/api. needed if nginx is handling ssl termination
    - PREFECT_LOGGING_LEVEL=DEBUG
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      prefect:
  
  postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    userns_mode: keep-id:uid=70,gid=70 # tell podman to use the postgres user

    environment:
      - POSTGRES_USER=prefect_user
      - POSTGRES_PASSWORD=${PREFECT_DB_PW}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      prefect:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      prefect:
  
  tiled:
    image: ghcr.io/bluesky/tiled:v0.1.0a113
    ports:
      - "127.0.0.1:8000:8000"

networks:
  prefect:
    driver: bridge