version: "3.3"
services:
  prefect:
    image: prefecthq/prefect:2.14-python3.11
    command: prefect server start
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${PREFECT_DB_USER}:${PREFECT_DB_PW}@prefect_db:5432/${PREFECT_DB_NAME} # Needed if using postgres and not sqlite
      # - PREFECT_UI_API_URL=https://localhost/api. needed if nginx is handling ssl termination
      - PREFECT_LOGGING_LEVEL=DEBUG
    ports:
      - 4200:4200
    depends_on:
      - prefect_db
    networks:
      mle_net:


  prefect_db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=${PREFECT_DB_USER}
      - POSTGRES_PASSWORD=${PREFECT_DB_PW}
      - POSTGRES_DB=${PREFECT_DB_NAME}
    volumes:
      - ./data/prefect_db:/var/lib/postgresql/data:rw
    restart: unless-stopped
    networks:
      mle_net:

  tiled:
    # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
    image: ghcr.io/bluesky/tiled:v0.1.0a114
    ports:
      - "8000:8000"
    environment:
      - TILED_DB_USER=${TILED_DB_USER}
      - TILED_DB_PW=${TILED_DB_PW}
      - TILED_DB_NAME=${TILED_DB_NAME}
      - TILED_DB_SERVER=${TILED_DB_SERVER}
      - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
    volumes:
      - ./tiled/deploy:/deploy
      - ./data/tiled_storage:/tiled_storage
    depends_on:
      - tiled_db
    networks:
      mle_net:


  tiled_db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=${TILED_DB_USER}
      - POSTGRES_PASSWORD=${TILED_DB_PW}
      - POSTGRES_DB=${TILED_DB_NAME}
    volumes:
      - ./data/tiled_db:/var/lib/postgresql/data:rw
      - ./data/tiled_storage:/tiled_storage
    restart: unless-stopped
    networks:
      mle_net:

  tiled_ingest:
    build:
      context: ./mlex_tiled_ingest
    environment:
      - TILED_DB_USER=${TILED_DB_USER}
      - TILED_DB_PW=${TILED_DB_PW}
      - TILED_DB_NAME=${TILED_DB_NAME}
      - TILED_DB_SERVER=${TILED_DB_SERVER}
      - TILED_INGEST_TILED_CONFIG_PATH=${TILED_INGEST_TILED_CONFIG_PATH}
      - TILED_INGEST_RMQ_HOST=${TILED_INGEST_RMQ_HOST}
      - TILED_INGEST_RMQ_USER=${TILED_INGEST_RMQ_USER}
      - TILED_INGEST_RMQ_PW=${TILED_INGEST_RMQ_PW}

    volumes:
      - ./mlex_tiled_ingest:/app
      - ./tiled/deploy:/deploy
      - ./data/tiled_storage:/tiled_storage

  mlex_segmentation:
    image: ghcr.io/mlexchange/mlex_highres_segmentation:main
    environment:
      - DATA_TILED_URI=http://tiled:8000/
      - DATA_API_KEY=${TILED_API_KEY}
      - USER_NAME=${MLEX_SEGM_USER}
      - USER_PASSWORD=${MLEX_SEGM_PW}
    ports:
      - 8075:8075
    # depends_on:
    #   - tiled
    # Intermediate solution restarting frontend on failure due to connection issues
    restart: always
    networks:
      mle_net:

  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "127.0.0.1:8161:8161" # Admin console
      - "127.0.0.1:61616:61616" # OpenWire
      - "127.0.0.1:61613:61613" # STOMP
  # rabbitmq:
  #   # command: sleep 888888
  #   image: rabbitmq:3-management-alpine
  #   # userns_mode: keep-id:uid=100,gid=100 # tell podman to use the rabbitmq user
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 127.0.0.1:5672:5672
  #       - 127.0.0.1:15672:15672 qi
  #   volumes:
  #       - ./rabbitmq/data/:/var/lib/rabbitmq/
  #       - ./rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #     mle_net:
  
networks:
  mle_net:
    driver: bridge
