version: "3.3"
services:
  prefect:
    image: prefecthq/prefect:2.14-python3.11
    command: prefect server start
    # command: sleep 99999
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${PREFECT_DB_USER}:${PREFECT_DB_PW}@prefect_db:5432/${PREFECT_DB_NAME} # Needed if using postgres and not sqlite
      # - PREFECT_UI_API_URL=https://localhost/api. needed if nginx is handling ssl termination
      - PREFECT_LOGGING_LEVEL=DEBUG
    ports:
      - 127.0.0.1:4200:4200
    depends_on:
      - prefect_db
    networks:
      mle_net:


  prefect_db:
    image: postgres:14.5-alpine
    userns_mode: keep-id:uid=70,gid=70 # tell podman to use the postgres user
    environment:
      - POSTGRES_USER=${PREFECT_DB_USER}
      - POSTGRES_PASSWORD=${PREFECT_DB_PW}
      - POSTGRES_DB=${PREFECT_DB_NAME}
    volumes:
      - ./data/prefect_db:/var/lib/postgresql/data:rw
    restart: unless-stopped
    networks:
      mle_net:


  tiled:
    # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
    image: ghcr.io/bluesky/tiled:v0.1.0a113
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - TILED_DB_USER=${TILED_DB_USER}
      - TILED_DB_PW=${TILED_DB_PW}
      - TILED_DB_NAME=${TILED_DB_NAME}
    volumes:
      - ./tiled/deploy:/deploy
      - ./data:/storage/data
    depends_on:
      - tiled_db
    networks:
      mle_net:


  tiled_db:
    image: postgres:14.5-alpine
    userns_mode: keep-id:uid=70,gid=70 # tell podman to use the postgres user
    environment:
      - POSTGRES_USER=${TILED_DB_USER}
      - POSTGRES_PASSWORD=${TILED_DB_PW}
      - POSTGRES_DB=${TILED_DB_NAME}
    volumes:
      - ./data/tiled_db:/var/lib/postgresql/data:rw
      - ./data/tiled_storage:/tiled_storage
    restart: unless-stopped
    networks:
      mle_net:


  mlex_segmentation:
    image: ghcr.io/mlexchange/mlex_highres_segmentation:latest
    environment:
      - TILED_URI=http://tiled:8000/
      - TILED_API_KEY=${TILED_API_KEY}
      - USER_NAME=${MLEX_SEGM_USER}
      - USER_PASSWORD=${MLEX_SEGM_PW}
    ports:
      - '8075:8075'
    depends_on:
      - tiled
    # Intermediate solution restarting frontend on failure due to connection issues
    restart: always
    networks:
      mle_net:


networks:
  mle_net:
    driver: bridge
